### ISSUE TITLE
Waiting for infinite Authy status request.

### ISSUE THREAD

**Issue by omeryounus** [AuthySE/Authy-demo#2]
I am ran into the following issue when creating the user. User created fine but it then enter into infinite loop for authy status waiting. Although I have approve the request from on mobile but it didn't move forward.

Please see below chrome developer view showings the continuous request for authy status.

![unnamed](https://cloud.githubusercontent.com/assets/6695770/20222478/ee8e8d3e-a84e-11e6-9419-dbf6bbc3dbf7.jpg)

**Comment by josh-authy** [comment]
Anything in the logs?

**Comment by omeryounus** [comment]
Yes, this is the continuous logs...

Express server started on *:3000
::1 - - [11/Nov/2016:17:14:03 +0000] "POST /session HTTP/1.1" 200 148 "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
::1 - - [11/Nov/2016:17:14:03 +0000] "GET /authy/status HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
::1 - - [11/Nov/2016:17:14:03 +0000] "GET /authy/status HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
::1 - - [11/Nov/2016:17:14:03 +0000] "GET /authy/status HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
......
......
.....

**Comment by josh-authy** [comment]
Hi @omeryounus,

I was able to get the app fully working on a Windows 7 VM without any changes.   Can you check your mongodb instance and make sure the user was properly registered?   There should be an AuthyID for your phone number/country code.   Additionally, could you find the error in the very beginning of your logs.  Specifically the logged information that occurs when you click "login" with the username and password.

Cheers,
- Josh @ Authy

**Comment by josh-authy** [comment]
Hey @omeryounus,
I just noticed the screen capture above isn't this repo's demo.  That looks like a Twilio demo setup...  not the demo this Github repo is providing.   Our demo uses the Authy logo as a favicon, doesn't use the same copy and uses the HTML5 push state not the hashbang I see above.  e.g. #login 

Lastly, this demo uses Angular and it looks like the call you're referencing is for jQuery.   You may want to hop over to a different repo to report this issue.

Cheers,
- Josh @ Authy
