### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by MihaelN** [AuthySE/Authy-demo#5]
Hi. I have followed README file and made first part of phone verification work. However, i get strange error in console when I run 2fa part of the app. I can register user and login but when I login and want to verify user, i get this error: 

RL:  User logged in
Send SMS
Unhandled rejection ValidationFailedError: Validation Failed
    at validate (C:\Users\USER\Desktop\demoAuth\node_modules\authy-client\dist\src\validator.js:74:11)

It seems to me that there is something missing since function making API call is set to be : 
 $scope.sms = function () {
        $http.post('/api/authy/sms')
            .success(function (data, status, headers, config) {
                console.log("SMS sent: ", data);
            })
            .error(function (data, status, headers, config) {
                console.error("SMS error: ", data);
                alert("Problem sending SMS");
            });
    };
There is no actuall data being sent and i dont have 'api' folder in my project. Tried it on both mac and windows and still didnt make it work.

**Comment by josh-authy** [comment]
Hi MihaelN,

Can you make sure you've pulled the most recent commit from master?

Regarding the 'api' folder, the API prefix is added too all defined routes when you initialize the node server.  You can see a comment here:
https://github.com/AuthySE/Authy-demo/blob/master/index.js#L162

Which version of Node are you using to run the demo?

**Comment by MihaelN** [comment]
I use node v6.8.0, And yes i pulled newest from master. I actually tried to do it 4/5 time from scratch on multiple machines and I still get same error.

edit: When I press 'send sms' on 2fa page i can see there is request called sms being sent but it says pending and after 3/4 min it times out. It looks like it doesn't send any data at all, it looks like request is empty.

**Comment by josh-authy** [comment]
Email me your phone number (country code, number) and I'll see if I can send a notification from my own machine.  josh [a.t.] twilio.com

**Comment by MihaelN** [comment]
Problem is that my api call is empty, I am not sending any data and my request is pending until timed out, no matter what i type in form. I tested with multiple country phonenumbers and none ov them seem to work.

**Comment by josh-authy** [comment]
Is there any error in your Node (server) logs during registration or when attempting a 2FA SMS?
Do you get an AuthyID back after registering with a username/password?

Perhaps you could try one of the scripts here with your phone number and country code:
https://github.com/AuthySE/Authy-API-Samples

**Comment by AlexanderKozhevin** [comment]
I got the same problem with 2FA thing. 
Anyway the phone verification stuff worked well.

When I tried to get registered, I got an error.
```
(node:4045) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Unhandled rejection ValidationFailedError: Validation Failed
    at validate (/root/Authy-demo/node_modules/authy-client/dist/src/validator.js:74:11)
    at _bluebird2.default.try (/root/Authy-demo/node_modules/authy-client/dist/src/client.js:636:31)
    at tryCatcher (/root/Authy-demo/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/root/Authy-demo/node_modules/bluebird/js/release/method.js:39:29)
    at Client.registerUser (/root/Authy-demo/node_modules/authy-client/dist/src/client.js:621:34)
    at /root/Authy-demo/server/controllers/users.js:104:23
    at /root/Authy-demo/node_modules/mongoose/lib/model.js:3737:16
    at /root/Authy-demo/node_modules/mongoose/lib/services/model/applyHooks.js:146:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Ok, but account has been registered anyway. So it means that smth nasty going on during registration process.

**Comment by AlexanderKozhevin** [comment]
Never mind 😄 
Looks, like I'm stupid.
I used numbers instead of letters for country.

**Comment by josh-authy** [comment]
@AlexanderKozhevin Hmm.  I've definitely used numbers before (and country abbreviations).  This may actually be a bug.  Let me check it out.

**Comment by LuqmanSahaf** [comment]
@AlexanderKozhevin Looks like I'm stupid too 😛 
Solved the problem

**Comment by josh-authy** [comment]
If you're having trouble, make sure you have the latest version of the authy-client package.  I've had no issues with 1.0.10.

**Comment by aman750** [comment]
Is this issue resolved ? i am also struck on the same part..need help !

**Comment by josh-authy** [comment]
@AlexanderKozhevin @MihaelN @aman750 

A small subset of users has this particular problem. I haven't been able to reproduce it but it does seem to be an issue with the Seegno library.  As such, I've replaced that library with one from [evilpacket/node-authy](https://github.com/evilpacket/node-authy).  It isn't as robust of a library but honestly that seems a like a strength at this point.

Do a `git pull` and `npm update` on master to update everything.
